            - name: Set Repo Secrets and Variables
  # You may pin to the exact commit or the version.
  # uses: howlowck/set-secrets-action@2972469e052584545d97a9f620a69df928785346
  uses: howlowck/set-secrets-action@1.4.0
  with:
    # Repository owner (individual or organization)
    repo-owner: adhulms07-web
    # Repository name
    repo-name: project1
    # Set secrets from environment variables, the format is "TARGET_SECRET_NAME=ENV_NAME", separated by spaces
    secrets-from-env: adhbibi , akms# optional, default is 
    # Set variables from environment variables, the format is "TARGET_SECRET_NAME=ENV_NAME", separated by spaces
    vars-from-env: # optional, default is 
    # GitHub Security Token. It is this identity that sets the secrets to the target repository. The scope for Classic PAT should include "repo" and "workflows". For fine-grain PAT, set "actions", "secrets", "variables", "environments" to "read and write" permissions.
    security-token: 
          
