            - name: Set Repo Secrets and Variables
  uses: howlowck/set-secrets-action@1.4.0
  with:
    repo-owner: adhulms07-web
    repo-name: project1
    secrets-from-env: ADHBIBI , AKMS# optional, default is 
    vars-from-env: 
    security-token: 
          
